# Generated by Django 3.2.16 on 2025-05-31 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20250531_0159'),
        ('blog', '0004_post_image'),
    ]

    operations = [
    ]
